# Generated by Django 5.0.6 on 2024-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('stationname', models.CharField(max_length=100)),
                ('highlights', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='stationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=200)),
                ('longitude', models.FloatField(max_length=200)),
                ('chargeprice', models.FloatField(max_length=100)),
                ('charger1', models.CharField(blank=True, max_length=50, null=True)),
                ('charger2', models.CharField(blank=True, max_length=50, null=True)),
                ('charger3', models.CharField(blank=True, max_length=50, null=True)),
                ('charger4', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
